version: "3.8"
services:
    ym-player:
        # image 뒤의 태그를 개발 중인 브랜치의 이름으로 설정해주세요.
        # 예시: binn328/ym-player:add-album
        image: binn328/ym-player:library-player8
        #restart: always
        user: root
        ports:
            - 8080:8080
        volumes:
            - ./ym-data:/data
        environment:
            - MONGO_USERNAME=admin
            - MONGO_PASSWORD=1234
        depends_on:
            - mongodb
    mongodb:
        image: mongo:latest
        #restart: always
        ports:
            - 27017:27017
        volumes:
            - ./mongo-data:/data/db
        environment:
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=1234
            - MONGO_INITDB_DATABASE=stock

    mongo-express:
        image: mongo-express
        #restart: always
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: admin
            ME_CONFIG_MONGODB_ADMINPASSWORD: 1234
            ME_CONFIG_MONGODB_URL: mongodb://admin:1234@mongodb:27017
