version: '3.8'
services:
  ym-player:
<<<<<<< HEAD
    image: binn328/ym-player:compose-test
=======
    image: binn328/ym-player:0.2.5
>>>>>>> 6171726feaee7992f2245c3964be3a5939707e1a
    #restart: always
    user: root
    ports:
      - 8080:8080
    volumes:
      - ./ym-data:/data
    environment:
      - MONGO_USERNAME=admin
      - MONGO_PASSWORD=1234
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    #restart: always
    ports:
      - 27017:27017
    volumes:
      - ./mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=1234
      - MONGO_INITDB_DATABASE=stock

  mongo-express:
    image: mongo-express
    #restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: 1234
      ME_CONFIG_MONGODB_URL: mongodb://admin:1234@mongodb:27017